apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: java-secretstore
  namespace: pet-clinic-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: java-sa