apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mysql-secretstore
  namespace: pet-clinic-db
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: mysql-sa